### ISSUE TITLE
Perl 6 to Raku timeframe

### ISSUE THREAD

**Issue by hankache** [perl6/problem-solving#118]
Any timeline regarding the Perl 6 -> Raku change for community resources?
I am mainly asking because I need to update https://perl6intro.com and a couple of syntax highlighters.
Should I update now? Later on? Keep both versions?
What is the consensus here?

**Comment by AlexDaniel** [comment]
There's a guide for module developers which mentions some things that are relevant to you: https://github.com/perl6/problem-solving/blob/master/solutions/language/Path-to-Raku.md#draft-guide-for-module-developers

Basically, you can change all plaintext references and I recommend doing that now. File extensions, executable name, some urls, etc. cannot be changed because nothing supports that *yet*. For example, [this doc PR](https://github.com/perl6/doc/pull/3056) was rejected for now, but meanwhile anything that mentions “Perl 6” in the docs is changed to talk about “Raku” (it's not live yet, but it's on master).

> a couple of syntax highlighters

These should start understanding new extensions as well as `raku` in the shebang. The name should be changed too (`raku-mode`, “Raku syntax highlighter”, etc.)

**Comment by JJ** [comment]
El mié., 16 oct. 2019 a las 13:06, Aleks-Daniel Jakimenko-Aleksejev (<
notifications@github.com>) escribió:

> There's a guide for module developers which mentions some things that are
> relevant to you:
> https://github.com/perl6/problem-solving/blob/master/solutions/language/Path-to-Raku.md#draft-guide-for-module-developers
>
> Basically, you can change all plaintext references and I recommend doing
> that now. File extensions, executable name, some urls, etc. cannot be
> changed because nothing supports that *yet*. For example, this doc PR
> <https://github.com/perl6/doc/pull/3056> was rejected for now, but
> meanwhile anything that mentions “Perl 6” in the docs is changed to talk
> about “Raku” (it's not live yet, but it's on master).
>

It's live (for the time being, and possibly also in the future) at
https://rakudocs.github.io As soon as we get new domains with raku on them,
I'll start to deploy it there.

**Comment by duncand** [comment]
I'm ready to go and update all references in my own projects or websites to the new name but I consider having a canonical web address to link to for Raku just as perl6.org was to be essential to updating my stuff, as I need something proper to reference.

I consider *.perl6.org to be the official main Perl 6 website/domain and believe that this is one of the very earliest things that needs an update to a new domain such as *.raku.org but otherwise having identical structure and content, besides s/Perl 6/Raku/ of the text.  And the old domains would 301 redirect to these.

**Comment by AlexDaniel** [comment]
@hankache is there still a question?

**Comment by hankache** [comment]
@AlexDaniel All clear. Thanks
