### ISSUE TITLE
Documentation principles for making translation easier

### ISSUE THREAD

**Issue by sjn** [perl6/problem-solving#78]
# On translation of the Perl 6 documentation

Translating the documentation is  a huge task, so I would like to suggest to adopt a few rules to make the life of translators a little easier.

1. Stop using the 80-character width re-flowing of text. Instead, require that each line only contains 1 (one) sentence, and that each sentence covers only 1 (one) point/topic/item.

Rationale: Identifying text that has changed by looking at diffs requires a lot more attention when the text is being re-flowed. A small change at the beginning of a paragraph can result in a diff covering multiple lines, and finding the actual change (even with word-diff) can quickly take significantly more effort then if the change didn't trigger a re-flow. This might not be much of a deal for small infrequent changes, but these add over time. We should assume that the translators do NOT constantly follow changes in the documentation, but rather do "batch work" - meaning they'll set aside an afternoon and go through lots of changes (maybe last month's, or longer!), instead of constantly monitoring & updating their translation as upstream is updated.

2. If sentence length is an issue (for whatever reason), then rewrite the long sentence into 2 or more shorter ones, and place each on their own lines.

Rationale: Long lines can still be an issue, especially for editors that don't handle them well. To work around this, I suggest trying to rewrite these long sentences into two or more shorter ones. This also improves readability of the text in general, and opens up for trivial calculation of readability scores like the [Flesch-Kincaid readability tests](https://en.wikipedia.org/wiki/Flesch%E2%80%93Kincaid_readability_tests).

3. Don't use invisible characters other than regular space ("\c[SPACE]") and UNIX newline ("\c[LINE FEED]").
4. When non-breaking space ("\c[NO-BREAK SPACE]") is needed (e.g. when writing "Perl 6"), then apply these automatically.
5. When other line endings (e.g. Windows "\c[CARRIAGE RETURN]\c[LINE FEED]") or other types of whitespace is encountered, we automatically fix those.

Rationale: It's also important to make it easy/trivial for "one-off" (drive-by) volunteers to easily help fix minor issues in documentation. One important way for this, is to make it trivial to use the web editor on github, but this creates limitations on which types of characters are possible to enter into the web form in order to offer a fix. While Perl 6 is by default embraces Unicode, we can't always assume this from editors out in the wild. Therefore, let's avoid common problematic characters and instead convert automatically (e.g. using git hooks or some other way) as needed.

# Purpose of these rules

The purpose with rules like these is to make the long-term life of translators and documentation volunteers easier. Translation, like documentation, should be considered an ongoing effort, and since we are fully dependent on volunteers, let's make their lives as easy as possible. We need them to stick around for the long run, and make it easier for new volunteers to get started. These rules should be shaped to improve the likelihood of this.

**Comment by sjn** [comment]
Here's an [example of what rule 1 above can look like](https://github.com/perl6/doc/blob/master/doc/Language/community.pod6).

**Comment by alabamenhu** [comment]
These are good ideas — I would like us to actually push this further, although that would require a lot of consensus on the part of documentation writers.

Things like standardizing certain terms, maybe agreeing for examples to use certain simple, easily translatable examples: e.g., using basic fruits (apple, banana, orange) for array examples and avoiding (well-intentioned) cutesy examples.  To some extent we have done this in the [style guide](https://github.com/perl6/doc/blob/master/writing-docs/STYLEGUIDE.md), but it doesn't concern as much of the things that ultimately will aide translation.  As an added benefit, almost anything that ends up aiding translatability will end up making documentation clearer. 

As well, it might not be a bad idea to keep a running page of examples of copytext that could be improved with ways to improve it.  That way new documentation editors can reference it and see what works better.

**Comment by JJ** [comment]
I appreciate your concern for documentation. However
* This would need a big effort in the shape of tests for changes (xt or simple tests), as well as an effort changing what's actually there to adapt it to these rules. We simply don't have the resources to do that.
* I don't see a clear need for that. Volunteers already do changes all the time. We could have more of them, of course, but that would need more of a marketing effort than changes on the source. You need to actually be interested in making a change before source layout encourages you (or puts you off).
* There's a single translation going on, in Chinese, and it's mainly focused on the tutorials, not on the reference. 

I'd had been happy with this had it been proposed from the get go. At this point, it represents a lot of effort to a return that is quite uncertain. So if there are not any more opinions, I propose to close this issue.

**Comment by sjn** [comment]
> I appreciate your concern for documentation. However
> 
>     * This would need a big effort in the shape of tests for changes (xt or simple tests), as well as an effort changing what's actually there to adapt it to these rules. We simply don't have the resources to do that.

I'm imagining that some of the reorganizing can be done automatically. Would that help? I wouldn't mind putting something like that together.

>     * I don't see a clear need for that. Volunteers already make changes all the time. We could have more of them, of course, but that would need more of a marketing effort than changes on the source. You need to actually be interested in making a change before source layout encourages you (or puts you off).

When it comes to translation I don't think we'll get very far with just the ones that are already involved. How many languages do we the current volunteers know? Personally, I would just assume that translating to any and all languages is desirable, and optimizing for the general case.

Furthermore, I don't think questions about marketing are relevant for this discussion. Sure, we need more of that too, but this fact doesn't influence the actual work amount and difficulty of any tranlations.

>     * There's a single translation going on, in Chinese, and it's mainly focused on the tutorials, not on the reference.

Since you're mentioning this, should I understand that you mean translating the reference isn't desirable?


> I'd had been happy with this had it been proposed from the get go. At this point, it represents a lot of effort to a return that is quite uncertain. So if there are not any more opinions, I propose to close this issue.

Assuming parts of this task can be automated, would this change your mind? As for the potential result, it wouldn't take many calories to ask a few translators if one is more convenient than the other...

**Comment by JJ** [comment]
>Premature optimization is the root of all evil

That's Donald Knuth. 

Essentially you are requesting that we optimize line and sentence length in the existing documentation for translation. However, I don't see any significant translation effort happening now, or in the foreseeable future. I haven't seen any request for any kind of change or adaptation in the existing documentation to accommodate translation. As a matter of fact, there's a partial translation to Chinese which has done quite well without any need to perform this change.

Additionally, optimizing in one direction means de-optimizing in another. Right now, 80-character lines have been imposed pretty much anywhere, as in any other code repo, so that it's easier to evaluate pull requests, basically to check diffs out, and of course to read and review existing code with existing editors (most editor will wrap lines for you, but GitHub will not). So if this was approved, it would be basically, as we say in Spain, "getting one saint naked to dress another". Except that one saint does exist and the other (the translator) might be a mythical creature.

Of course I agree with you with making sentences shorter, and maybe easier to understand. However, that's difficult to implement all across the board. Do we make changes that lower the Flesch-Kincaid readability score fail? Do we establish a level and change all the existing documents to get to that level? 

Again, I'm very grateful for this suggestion (and any other directed at improving the documentation), but I again propose closing this issue.

**Comment by sjn** [comment]
> [Deleted some wrong and irrelevant stuff]

There's too much wrong and irrelevant in what you wrote, so I'll leave you with a link to a repo where you can [explore what different diffs look like when using different wrapping/flow/length policies](https://github.com/sjn/example-about-editing-docs).

> Of course I agree with you with making sentences shorter, and maybe easier to understand. However, that's difficult to implement all across the board. Do we make changes that lower the Flesch-Kincaid readability score fail? Do we establish a level and change all the existing documents to get to that level?

No need to make tests fail unless we decide that a rule has to be enforced automatically.

> Again, I'm very grateful for this suggestion (and any other directed at improving the documentation), but I again propose closing this issue.

Take a look at the repo I made, and remember to check out diffs/changes between earlier commits, since each commit tries to do something different.

**Comment by JJ** [comment]
@sjn OK, so we've decided to stop arguing about what the objective of changing a whole repository (and (so far *de facto*) policy) and now we're decided the relative merits of different wrapping/flow/length policies.

Just a couple of things: one thing is to decide what policy to follow *ab initio*, a different thing is to decide to change a policy. Second, we *do* decide that rules need to be enforced automatically, we simply don't have the resources to do that by hand (although Coke does a pretty good job of enforcing rules that are enforced through author tests).

Please realize that you're asking for a change of policy for an objective that simply does not exist, trying to solve an issue that has not arisen in the repository or anywhere else, by people that have actually put some work in the repository or, for that matter, no one.

So, again, thanks for the suggestion, but no thanks. I'm closing this issue now, since I don't think this discussion is actually relevant in this repository. If you want to raise this issue again in the docs repo itself, I'll be happy to address it, as long as you're actually interested in solving a real problem and not on proving you're right and I'm wrong.
