### ISSUE TITLE
Unification of Array/List and Hash/Map behaviors.

### ISSUE THREAD

**Issue by vrurg** [perl6/problem-solving#99]
Initiated by rakudo/rakudo#3168

`Array` and `Hash` can be roughly described as mutable versions of `List` and `Map`. From this respect one can say they're similar. Correspondingly, we can expect similar behavior in similar situations from them. But as a matter of fact, there're pretty significant differences with respect to how they handle containers.

First example:

```
my $h = {a=>1, b=>2}; my %h = $h; say %h; # {a => 1, b => 2}
my $a = [1,2]; my @a = $a; say @a; # [[1 2]]
```

Second example is valid on `HEAD` where `Map` doesn't decontnainerzie implicitly:

```
my @a = <1 2>; say @a.List[0].VAR.^name; # IntStr
my %h = a=>1, b=>2; say %h.Map<a>.VAR.^name' # Scalar
```

**Comment by vrurg** [comment]
# Proposed Solution

## First case

Assignment to an array must be handled similarly to assignment to a hash. I.e. RHS must be decontainerzied and handled accordingly to the value type. If an array on RHS needs to be stored as an LHS array element there two solutions to this depending on what exactly is needed:

```
my $a = [1,2];
@a = [ $a ];
@a[0] = $a;
```

## Second case 

`Hash` coercion to `Map` must decontainerize values. This seems logical not only because this is what `Array.List` does but because as coercion to `Map` is in a way can be considered an operation opposite to assignment to the hash from the containerization point of view.

**Comment by jnthn** [comment]
The two things I'd say are fairly clear are:

* Construction of a new `Map`/`List` should preserve containers (or the lack of them)
* Coercion from `Array` -> `List` and `Hash` -> `Map` should drop the containers

The second of these is arguably not the best bit of API design; really a coercion to a type that something already is should return identity. But it's where we've ended up with `Array.List`, it's a behavior `Hash.Map` similarly had (and we should restore), it's widely in use, and I think we can live with it. So that answers case 2 (and clarifies the thing we fixed recently, which was `Map` construction wrongly decontainerizing).

Case 1 is about neither construction nor coercion, but assignment. I think the current situation is pragmatic, though arguably to a fault. :-)

The array case is the one I think is clearly correct here; we've taken care in numerous places to make sure an itemized array won't go flattening, but be treated as a single element, and we don't want a discontinuity on that in array assignment.

For hashes, we *could* in principle rule that any assignment of a single item (that is, in a `Scalar` container) into a hash must die, because you always need at least two things (a key and a value). However, itemization rules are primarily of interest with lists (and controlling flattening) rather than hashes (where the presence of a key disambiguates maters), so probably making the assignment into the hash die would put is in foolish consistency territory.

More generally, assignment is a copying operation *into* a target, and the target decides on the semantics of the assignment (by implementing `STORE`) - a bit like how with smartmatch the RHS determines the semantics through `ACCEPTS`. In that sense, then, it can be considered reasonable that data structures that can be assigned into make locally sensible choices of how to interpret the assignee.

**Comment by niner** [comment]
FWIW I added the `List` method to `Array` for when some rakudo method uses an `Array` to collect some results but wants to return a plain non-modifiable `List` to not leak such an implementation detail. We already had `list` returning self and I didn't really know about coercers back then.

The irony is that we didn't use it for that purpose (much) afterwards because as a generic method it cannot just assume that it can reuse `$!reified` from the `Array` which is what we usually want to do for better performance.

**Comment by vrurg** [comment]
Proposed fix implementation is in rakudo/rakudo#3174, tests are in perl6/roast#575.

**Comment by vrurg** [comment]
The long-running discussion about wether `Map` must or must not decont its values and recent conversation with @lizmat resulted in a very simple thought: perhaps it worth having alternative structures which would be value types, contrary to `List`/`Map`? @lizmat has already published `Tuple` for value type list. By merging rakudo/rakudo#3174 it is now possible to implement `Dict` type with just eight lines of code, including curlies:

```
class Dict is Map {
    multi method new(Dict: *@args --> Dict:D) {
        self.Map::new.STORE(@args, :INITIALIZE, :DECONT);
    }

    method STORE (|c) {
        self.Map::STORE(|c, :DECONT);
    }
}
```

Similar support for `:DECONT` could be implemented for `List` too making `Tuple` implementation similar to the above example.

The whole point is that both approaches to these basic data types are rightful to exists. So, why can't they co-exists?

**Comment by vrurg** [comment]
As the initial purpose of this issue was resolved, I forked the question about value types into a separate issue #135. This one can be closed now.
